name: Deploy to GAE
on:
  push:
    branches: [master]
  pull_request:

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Set Up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: Checkout
        uses: actions/checkout@v4

      - name: NPM Install
        run: npm install && npm run build

      - name: App Engine auth
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v1
        with:
          deliverables: app.yaml
          version: v1
          project_id: ${{ secrets.GCP_PROJECT }}
